pipeline {
    agent {
        dockerfile {
            filename 'ci/Dockerfile'
            args '--gpus 1'
            label 'docker && v100'
        }
    }
    options {
        timeout(time: 1, unit: 'HOURS')
    }
    environment {
        HOME = "$WORKSPACE"
    }
    stages {
        stage('Build') {
            environment {
                CMAKE_ARGS = "-DJAX_FINUFFT_USE_CUDA=ON"
            }
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -U pip
                    pip install -U "jax[cuda12]"
                    pip install -v ".[test]"
                '''
            }
        }
        stage('CPU Tests') {
            environment {
                JAX_PLATFORMS = "cpu"
                OMP_NUM_THREADS = "${env.PARALLEL}"
            }
            steps {
                sh '''
                    . venv/bin/activate
                    pytest -v tests/
                '''
            }
        }
        stage('GPU Tests') {
            environment {
                JAX_PLATFORMS = "cuda"
                OMP_NUM_THREADS = "${env.PARALLEL}"
            }
            steps {
                sh '''
                    . venv/bin/activate
                    pytest -v tests/
                '''
            }
        }
    }
}
